#!/usr/bin/env python3
"""
clustering_heatmap.py
=====================
Analyze whole-chromosome Hi-C interaction frequencies using raw contact counts
from HiC-Pro allValidPairs files.  Builds a chromosome-by-chromosome interaction
matrix, applies optional normalization, performs hierarchical clustering, and
generates clustered heatmaps.

Supports pre-PDE samples (intact germline genome, fewer chromosomes) and
post-PDE samples (fragmented somatic genome, more chromosomes) with separate
chromosome order files and configurable label font sizes for each.

Two normalization modes:
  --mccord   : Expected-trans normalization (McCord et al.).  For each pair
               (i,j), expected = 0.5 * (Ci*Cj/(T-Ci) + Ci*Cj/(T-Cj)) where
               Ci/Cj are row marginals and T is the grand total.
               Normalized value = observed / expected.
  --normalize: Row-max normalization (divide each row by its maximum).
  (default)  : No normalization (raw symmetric counts).

Outputs (per sample, in --output_dir):
  - Clustered heatmap (PNG + PDF)
  - Cluster assignments (TSV)

Dependencies:
  numpy, pandas, seaborn, matplotlib, scipy

Example usage:
  python clustering_heatmap.py \\
      --pre_pde_samples \\
          allValidPairs/AG.v50.1cell.allValidPairs \\
          allValidPairs/AG.v50.48hr.allValidPairs \\
          allValidPairs/AG.v50.60hr.allValidPairs \\
      --post_pde_samples \\
          allValidPairs/AG.v50.5day.allValidPairs \\
          allValidPairs/AG.v50.10day.allValidPairs \\
      --order_pre data/chrom_order_pre.txt \\
      --order_post data/chrom_order_post.txt \\
      --mccord \\
      --thresh 2.0 \\
      --label_fontsize_pre 22 \\
      --label_fontsize_post 16 \\
      --hide_row_dendrogram \\
      --dpi 300 \\
      --output_dir results/ \\
      --output_clusters clusters.bed \\
      --output_heatmap heatmap.png \\
      --output_table sorted.xlsx \\
      --output_matrix matrix.xlsx \\
      --output_combined combined.xlsx \\
      --output_pca pca.png \\
      --output_cluster_heatmap cluster_heatmap.png

Input files:
  --pre_pde_samples / --post_pde_samples: HiC-Pro allValidPairs files.
      Column 2 = query chromosome, column 5 = target chromosome.
      These are large files generated by HiC-Pro and are NOT included in the
      repository.  Raw reads are available from SRA under accession SRPXXXXXX;
      regenerate allValidPairs by running HiC-Pro.
  --order_pre / --order_post: Text files listing chromosome names in desired
      display order (one per line).  Included in the repository under data/.
"""

import argparse
import os
import re
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.spatial.distance import pdist

# Set Arial as default font
plt.rcParams['font.family'] = 'Arial'
plt.rcParams['font.sans-serif'] = ['Arial']
plt.rcParams['svg.fonttype'] = 'none'  # editable text in SVG for Illustrator

# -----------------------------
# Helper: Get base chromosome name (strip trailing lowercase letters)
# e.g. "chr01a" => "chr01"
# -----------------------------
def get_base(chrom):
    i = len(chrom)
    while i > 0 and chrom[i - 1].islower():
        i -= 1
    return chrom[:i]

# -----------------------------
# Helper: Convert value to float or -∞
# -----------------------------
def safe_float(val):
    try:
        return float(val)
    except Exception:
        return -np.inf

# -----------------------------
# Helper: Relabel clusters by frequency
# Largest cluster => label=1, next => label=2, etc.
# -----------------------------
def relabel_by_frequency(cluster_dict):
    freq = {}
    for chrom, label in cluster_dict.items():
        freq[label] = freq.get(label, 0) + 1
    sorted_labels = sorted(freq.items(), key=lambda x: x[1], reverse=True)
    mapping = {}
    new_label = 1
    for old_label, count in sorted_labels:
        mapping[old_label] = new_label
        new_label += 1
    out = {chrom: mapping[label] for chrom, label in cluster_dict.items()}
    return out

# -----------------------------
# Expected Normalization based on trans contact frequencies
# -----------------------------
def normalize_interaction_matrix_expected(raw_matrix):
    """ Normalize the raw interaction matrix using the expected-trans interaction model.
    For each cell (i,j) (i != j):
    - Compute C[i] as the sum of raw interactions for row i (marginal for chromosome i).
    - Let T be the grand total sum of all off-diagonal interactions.
    Then, the expected number of interactions between chromosomes i and j is:
    E_{ij} = 1/2 * ((C_i * C_j)/(T - C_i) + (C_i * C_j)/(T - C_j))
    The normalized value is defined as:
    norm_{ij} = observed_{ij} / E_{ij}
    Self-interactions (i == j) remain as NaN.
    """
    # Work on copies to avoid mutating the input
    raw_clean = raw_matrix.copy()
    norm_matrix = raw_matrix.copy()
    
    # First, ensure the raw matrix contains only scalars
    for i in raw_clean.index:
        for j in raw_clean.columns:
            val = raw_clean.at[i, j]
            if isinstance(val, pd.Series):
                raw_clean.at[i, j] = val.iloc[0] if len(val) > 0 else np.nan
    
    # Calculate marginal totals (using row sums)
    marginals = {}
    for chrom in raw_clean.index:
        row_vals = raw_clean.loc[chrom].values
        # Filter out NaN, inf, etc.
        valid_vals = [v for v in row_vals if np.isscalar(v) and np.isfinite(v)]
        marginals[chrom] = sum(valid_vals)
    
    # Calculate total sum of all off-diagonal interactions
    T = sum(marginals.values())
    
    for i in raw_clean.index:
        for j in raw_clean.columns:
            if i == j:
                continue  # skip self-interactions
            
            raw_val = raw_clean.at[i, j]
            # Make sure we have a scalar value
            if isinstance(raw_val, pd.Series):
                raw_val = raw_val.iloc[0] if len(raw_val) > 0 else np.nan
            
            if not np.isnan(raw_val) and np.isfinite(raw_val):
                C_i = marginals[i]
                C_j = marginals[j]
                # Avoid division by zero
                if abs(T - C_i) < 1e-10 or abs(T - C_j) < 1e-10:
                    expected = np.nan
                else:
                    expected = 0.5 * ((C_i * C_j)/(T - C_i) + (C_i * C_j)/(T - C_j))
                # If expected is very small, flag it to avoid division errors
                if abs(expected) < 1e-10:
                    norm_matrix.at[i, j] = np.nan
                else:
                    norm_matrix.at[i, j] = raw_val / expected
            else:
                norm_matrix.at[i, j] = np.nan
                
    return norm_matrix


# -----------------------------
# read the pairs files
# -----------------------------
def parse_pairs_files(pairs_files, target_chroms=None):
    counts = {}
    for pf in pairs_files:
        with open(pf, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line=line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts)<6:
                    continue
                query = parts[1]
                target = parts[4]
                if query==target:
                    continue
                if target_chroms is not None:
                    if (query not in target_chroms) and (target not in target_chroms):
                        continue
                counts.setdefault(query, {})
                counts[query][target] = counts[query].get(target,0)+1
    return counts

def read_order_file(order_file):
    out = []
    with open(order_file, 'r') as f:
        for line in f:
            line=line.strip()
            if line:
                out.append(line)
    return out

def build_interaction_matrix(counts, chrom_order):
    matrix = pd.DataFrame(0, index=chrom_order, columns=chrom_order, dtype=float)
    for q in counts:
        for t, cval in counts[q].items():
            if q in matrix.index and t in matrix.columns:
                matrix.at[q,t] = cval
    np.fill_diagonal(matrix.values, np.nan)
    return matrix

def symmetrize_matrix(raw_matrix):
    sym = (raw_matrix + raw_matrix.T)/2
    np.fill_diagonal(sym.values, np.nan)
    return sym

def normalize_symmetric_by_row_max(mat):
    mat = mat.copy()
    np.fill_diagonal(mat.values, np.nan)
    row_max = mat.max(axis=1, skipna=True)
    out = mat.divide(row_max, axis=0)
    return out

# Build sorted table
def build_sorted_interaction_table(matrix):
    rows=[]
    for q in matrix.index:
        interactions=[]
        for t in matrix.columns:
            if t==q:
                continue
            val = matrix.at[q,t]
            if not np.isscalar(val):
                try:
                    val = val.item()
                except (ValueError, AttributeError):
                    try:
                        val = float(val)
                    except (ValueError, TypeError):
                        val = np.nan
            sort_val = safe_float(val) if pd.notnull(val) else -np.inf
            interactions.append((t, sort_val, val))
        interactions.sort(key=lambda x: x[1], reverse=True)
        row = [q]
        for t,_,v in interactions:
            row.append(f"{t} ({v:.2f})")
            row.append(str(v))
        rows.append(row)
    max_len = max(len(r) for r in rows)
    for r in rows:
        while len(r)<max_len:
            r.append("")
    col_names = ["QueryChromosome"]
    for i in range(1, max_len):
        if i%2==1:
            col_names.append(f"Rank{i} (val)")
        else:
            col_names.append(f"Rank{(i)//2}_raw")
    return pd.DataFrame(rows, columns=col_names)

def build_matrix_table(matrix):
    df = matrix.copy()
    df.insert(0,"QueryChromosome", df.index)
    return df

def write_combined_excel(sorted_table, matrix_table, sample_name, out_file):
    import xlsxwriter
    with pd.ExcelWriter(out_file, engine='xlsxwriter') as writer:
        sorted_table.to_excel(writer, sheet_name="SortedInteractions", startrow=1, index=False)
        matrix_table.to_excel(writer, sheet_name="Matrix", startrow=1, index=False)
        ws_s = writer.sheets["SortedInteractions"]
        ws_m = writer.sheets["Matrix"]
        ws_s.write(0,0, f"Sample: {sample_name} - Sorted Interaction Table")
        ws_m.write(0,0, f"Sample: {sample_name} - Interaction Matrix")
    print(f"Combined Excel file saved to {out_file}")

def write_clusters(cluster_dict, out_file):
    df = pd.DataFrame(list(cluster_dict.items()), columns=["QueryChromosome","Cluster"])
    df.to_csv(out_file, sep="\t", index=False)
    print(f"Cluster assignments written to {out_file}")

def cluster_chromosomes(matrix, nclusters=None, thresh=None):
    matrix_filled = matrix.copy()
    for r in matrix_filled.index:
        row_arr = matrix_filled.loc[r].astype(float).values
        max_val = np.nanmax(row_arr)
        fill_val = (max_val+1) if not np.isnan(max_val) else 0
        matrix_filled.loc[r] = matrix_filled.loc[r].fillna(fill_val)
    dists = pdist(matrix_filled.values, metric="euclidean")
    Z = linkage(dists, method="complete")
    print("Linkage distances (for each merge):", Z[:, 2])
    if nclusters is not None:
        labs = fcluster(Z, t=nclusters, criterion="maxclust")
    elif thresh is not None:
        labs = fcluster(Z, t=thresh, criterion="distance")
    else:
        def_thresh = 0.7*np.max(Z[:,2])
        labs = fcluster(Z, t=def_thresh, criterion="distance")
    out = { rname: labs[i] for i,rname in enumerate(matrix.index)}
    return out, Z

def plot_heatmap(matrix, sample_name, out_file_base, dpi=600,
                 global_vmin=None, global_vmax=None, label_fontsize=12,
                 hide_row_dendrogram=False):
    """Generate clustered heatmap with hierarchical clustering on both axes.
    Saves both PNG and PDF versions.
    
    Parameters
    ----------
    global_vmin, global_vmax : float, optional
        If provided, use these as the shared colorscale limits across all plots.
    label_fontsize : int
        Font size for chromosome tick labels.
    hide_row_dendrogram : bool
        If True, hide the left-side (row) dendrogram to save horizontal space.
    """
    row_filled = matrix.copy()
    for r in row_filled.index:
        arr = row_filled.loc[r].astype(float).values
        max_val = np.nanmax(arr)
        fill_val = (max_val+1) if not np.isnan(max_val) else 0
        row_filled.loc[r] = row_filled.loc[r].fillna(fill_val)
    row_dists = pdist(row_filled.values, metric="euclidean")
    Z_rows = linkage(row_dists, method="complete")

    col_filled = matrix.copy().T
    for c in col_filled.index:
        arr = col_filled.loc[c].astype(float).values
        max_val = np.nanmax(arr)
        fill_val = (max_val+1) if not np.isnan(max_val) else 0
        col_filled.loc[c] = col_filled.loc[c].fillna(fill_val)
    col_dists = pdist(col_filled.values, metric="euclidean")
    Z_cols = linkage(col_dists, method="complete")

    mat_display = matrix.copy()
    cmap = sns.color_palette("viridis", as_cmap=True)
    cmap.set_bad("black")
    finite_vals = mat_display.values[np.isfinite(mat_display.values)]
    # Use global scale if provided, otherwise per-sample
    if global_vmin is not None and global_vmax is not None:
        min_val = global_vmin
        max_val = global_vmax
    else:
        min_val = np.min(finite_vals) if finite_vals.size > 0 else 0
        max_val = np.max(finite_vals) if finite_vals.size > 0 else 1
    norm_cont = mcolors.Normalize(vmin=min_val, vmax=max_val)

    g = sns.clustermap(
        mat_display,
        row_linkage=Z_rows,
        col_linkage=Z_cols,
        cmap=cmap,
        norm=norm_cont,
        vmin=min_val,
        vmax=max_val,
        figsize=(12,12)
    )
    r_order = g.dendrogram_row.reordered_ind
    c_order = g.dendrogram_col.reordered_ind
    r_labels = mat_display.index[r_order]
    c_labels = mat_display.columns[c_order]
    g.ax_heatmap.set_xticks(np.arange(len(c_labels)) +0.5)
    g.ax_heatmap.set_xticklabels(c_labels, fontsize=label_fontsize, rotation=90, family='Arial')
    g.ax_heatmap.set_yticks(np.arange(len(r_labels)) +0.5)
    g.ax_heatmap.set_yticklabels(r_labels, fontsize=label_fontsize, rotation=0, family='Arial')
    # Dendrogram styling
    if hide_row_dendrogram:
        g.ax_row_dendrogram.set_visible(False)
        # Reclaim the space: shrink the row dendrogram column
        g.gs.update(wspace=0.02)
    else:
        for line in g.ax_row_dendrogram.lines:
            line.set_linewidth(2)
    for line in g.ax_col_dendrogram.lines:
        line.set_linewidth(2)
    cbar = g.ax_heatmap.collections[0].colorbar
    cbar.set_ticks( np.linspace(min_val, max_val, num=5) )
    cbar.set_ticklabels([f"{x:.1f}" for x in np.linspace(min_val, max_val, num=5)], fontsize=10)
    cbar.ax.set_ylabel("Interaction Value", fontsize=12, family='Arial')

    g.fig.suptitle(
        f"Interaction Heatmap for Sample: {sample_name}\nRows=Query, Columns=Target (Self-interactions NaN)",
        y=1.15, fontsize=14, family='Arial'
    )
    
    # Save both PNG and PDF versions
    png_file = out_file_base.replace('.png', '') + '.png'
    pdf_file = out_file_base.replace('.png', '') + '.pdf'
    
    g.savefig(png_file, dpi=dpi, format='png')
    g.savefig(pdf_file, dpi=dpi, format='pdf')
    plt.close(g.fig)
    print(f"Heatmaps saved: {png_file} and {pdf_file}")

def write_mermaid_diagram(outdir):
    mermaid_code = '''```mermaid
flowchart TD
    A["Pre-PDE Samples"]
    B["Post-PDE Samples"]
    C["Build Raw Interaction Matrix\n(Use full order file)"]
    D["Symmetrize Matrix\n(Average with transpose)"]
    E["Normalization\n(--normalize: Row-Max\n--mccord: Expected-Trans)"]
    F["Individual Analysis:\nClustering, Heatmap, Excel"]
    A --> C
    B --> C
    C --> D
    D --> E
    E --> F
```'''
    mermaid_file = os.path.join(outdir, "mermaid_diagram.mmd")
    with open(mermaid_file,"w") as f:
        f.write(mermaid_code)
    print(f"Mermaid diagram saved to {mermaid_file}")

def compute_sample(pairs_file, group_tag, order_list, target_chroms, outdir, args):
    """Pass 1: Build and normalize matrix, run clustering, write cluster file.
    Returns (sample_name, final_matrix, cluster_dict)."""
    base_name = os.path.basename(pairs_file).replace(".allValidPairs","")
    samp_name = f"{base_name}_{group_tag}"
    counts = parse_pairs_files([pairs_file], target_chroms=target_chroms)
    # filter out chrM,chrUn
    counts = {
        c: {o:ct for o,ct in inter.items() if not (o.startswith("chrM") or o.startswith("chrUn"))}
        for c,inter in counts.items() if not (c.startswith("chrM") or c.startswith("chrUn"))
    }
    mat_raw = build_interaction_matrix(counts, order_list)
    mat_sym = symmetrize_matrix(mat_raw)
    
    # Apply normalization based on flags
    if args.mccord:
        mat_fin = normalize_interaction_matrix_expected(mat_sym)
    elif args.normalize:
        mat_fin = normalize_symmetric_by_row_max(mat_sym)
    else:
        mat_fin = mat_sym
        
    cdict,_ = cluster_chromosomes(mat_fin, nclusters=args.nclusters, thresh=args.thresh)
    cdict = relabel_by_frequency(cdict)
    cF = os.path.join(outdir, f"{samp_name}_{args.output_clusters}")
    write_clusters(cdict, cF)
    return samp_name, mat_fin, cdict

def get_global_range(matrices):
    """Compute the global min and max across a list of DataFrames (ignoring NaN/Inf)."""
    all_min, all_max = np.inf, -np.inf
    for mat in matrices:
        finite_vals = mat.values[np.isfinite(mat.values)]
        if finite_vals.size > 0:
            all_min = min(all_min, np.min(finite_vals))
            all_max = max(all_max, np.max(finite_vals))
    if all_min == np.inf:
        all_min, all_max = 0, 1
    return all_min, all_max

def main():
    parser = argparse.ArgumentParser(
        description="Analyze pre-PDE and post-PDE Hi-C data. "
                    "Generates heatmaps and Excel outputs for each sample."
    )
    parser.add_argument("--pre_pde_samples", nargs="+", required=True, help="List of pre-PDE allValidPairs files.")
    parser.add_argument("--post_pde_samples", nargs="*", default=[], help="List of post-PDE allValidPairs files.")
    parser.add_argument("--order_pre", required=True, help="Pre-PDE order file (24 lines).")
    parser.add_argument("--order_post", required=True, help="Post-PDE order file (36 lines).")
    parser.add_argument("--thresh", type=float, default=None, help="Clustering distance threshold.")
    parser.add_argument("--output_table", required=True)
    parser.add_argument("--output_matrix", required=True)
    parser.add_argument("--output_combined", required=True)
    parser.add_argument("--output_clusters", required=True)
    parser.add_argument("--output_heatmap", required=True)
    parser.add_argument("--output_pca", required=True)
    parser.add_argument("--output_cluster_heatmap", required=True)
    parser.add_argument("--nclusters", type=int, default=None)
    parser.add_argument("--target", type=str, default=None)
    parser.add_argument("--normalize", action="store_true", help="Use row-max normalization")
    parser.add_argument("--mccord", action="store_true", help="Use expected-trans (McCord) normalization (overrides --normalize)")
    parser.add_argument("--dpi", type=int, default=600)
    parser.add_argument("--output_dir", default="combined_output")
    parser.add_argument("--label_fontsize_pre", type=int, default=16,
                        help="Font size for chromosome labels on pre-PDE heatmaps (default: 16)")
    parser.add_argument("--label_fontsize_post", type=int, default=12,
                        help="Font size for chromosome labels on post-PDE heatmaps (default: 12)")
    parser.add_argument("--hide_row_dendrogram", action="store_true",
                        help="Hide the left-side (row) dendrogram to save horizontal space")

    args = parser.parse_args()
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    target_chroms = None
    if args.target:
        target_chroms = [ x.strip() for x in args.target.split(",") if x.strip() ]

    order_pre = read_order_file(args.order_pre)
    order_post = read_order_file(args.order_post)

    # ---- Pass 1: Compute all matrices ----
    pre_results = []   # list of (samp_name, mat_fin, cdict)
    post_results = []
    all_matrices = []  # for computing global color range

    print("=== Pass 1: Computing matrices and clusters ===")
    for pf in args.pre_pde_samples:
        samp_name, mat_fin, cdict = compute_sample(pf, "pre", order_pre, target_chroms, args.output_dir, args)
        pre_results.append((samp_name, mat_fin, cdict))
        all_matrices.append(mat_fin)

    for pf in args.post_pde_samples:
        samp_name, mat_fin, cdict = compute_sample(pf, "post", order_post, target_chroms, args.output_dir, args)
        post_results.append((samp_name, mat_fin, cdict))
        all_matrices.append(mat_fin)

    # Compute shared color scale across ALL samples
    global_vmin, global_vmax = get_global_range(all_matrices)
    print(f"\n=== Global color scale: vmin={global_vmin:.4f}, vmax={global_vmax:.4f} ===\n")

    # ---- Pass 2: Plot heatmaps with shared scale ----
    print("=== Pass 2: Plotting heatmaps with shared scale ===")
    for samp_name, mat_fin, cdict in pre_results:
        hF = os.path.join(args.output_dir, f"{samp_name}_{args.output_heatmap}")
        plot_heatmap(mat_fin, samp_name, hF, dpi=args.dpi,
                     global_vmin=global_vmin, global_vmax=global_vmax,
                     label_fontsize=args.label_fontsize_pre,
                     hide_row_dendrogram=args.hide_row_dendrogram)

    for samp_name, mat_fin, cdict in post_results:
        hF = os.path.join(args.output_dir, f"{samp_name}_{args.output_heatmap}")
        plot_heatmap(mat_fin, samp_name, hF, dpi=args.dpi,
                     global_vmin=global_vmin, global_vmax=global_vmax,
                     label_fontsize=args.label_fontsize_post,
                     hide_row_dendrogram=args.hide_row_dendrogram)

    print("\nAll samples processed. Heatmaps and cluster files saved to", args.output_dir)

if __name__=="__main__":
    main()
